### ISSUE TITLE
Release file not found

### ISSUE THREAD

**Issue by timvis** [mcmilk/uboot-utils#1]
I like to download but get an error from the Amazon file-cloud only. I tried to compile in several ways, but failed always (e.g. MIPS32r2, static, OenWRT Toolchain, gcc-5 and gcc-7). Got segfault, no response of the command-line or via sh '(expecting ")" )'.

Is it possible to provide a mirror for the binaries?

---
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>83976979/1e2f33d4-01bb-11e7-9aeb-71911da468b2</Key>
<RequestId>C8D14679BE6BF40E</RequestId>
<HostId>
6LBrLKrCuQmr4deYtUstvR9f1mJcyumWM/wh+tRWbIDZDCOUKfd46m6q7jV/YEe5z7FREW2e21w=
</HostId>
</Error>`

**Comment by mcmilk** [comment]
Yes, I just created a new 0.1 release ... I deleted my github account for some months... ;-)
